repos:
  # checks:
  # - executables with shebangs
  # - shebangs on non executables
  # - EOF
  # - sort imports
  # - black formatting
  # - black-jupyter formatting
  # - flake8 linting
  # - secret leaks
  # - large files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-added-large-files
      - id: end-of-file-fixer
        types: ["python"]
        files: lm_kbc
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--lbt, "1", --ls]
        types: ["python"]
        files: lm_kbc
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        types: ["python"]
        files: lm_kbc
      - id: black-jupyter
        language_version: python3
        types: ["jupyter"]
        files: lm_kbc
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        types: ["python"]
        files: lm_kbc
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.2.0
    hooks:
      - id: gitleaks
